# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  name: DmoTest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore Packages
  inputs:
    command: 'restore'
    projects: './LogHunter.csproj'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: Build Project
  inputs:
    command: 'build'
    projects: './LogHunter.csproj'

- task: DotNetCoreCLI@2
  displayName: Publish .exe
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: './LogHunter.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  displayName: Publish Artifact
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop'
